name: handstate
version: 0.1.0
description: Keeps track of a hand of multiplayer no limit holdem.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.7.0 <3.0.0"

dev_dependencies:
  test: ^1.15.6
